// Embed the markdown docs into a TS module so the superadmin console can render
// them WITHOUT filesystem/tracing surprises on Vercel (the TS is always bundled).
//   regenerate: npx tsx scripts/embed-docs.mts   (run after editing docs/*.md)
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";

const DOCS = {
  HLA: { title: "High-Level Architecture", file: "docs/HLA.md" },
  FEATURES: { title: "Feature Catalog", file: "docs/FEATURES.md" },
};

const out: Record<string, { title: string; content: string }> = {};
for (const [key, d] of Object.entries(DOCS)) {
  out[key] = { title: d.title, content: readFileSync(resolve(process.cwd(), d.file), "utf8") };
}

mkdirSync(resolve(process.cwd(), "lib/docs"), { recursive: true });
const ts =
  "// AUTO-GENERATED by scripts/embed-docs.mts — do not edit by hand.\n" +
  "// Regenerate after editing docs/*.md:  npx tsx scripts/embed-docs.mts\n" +
  "export const DOCS: Record<string, { title: string; content: string }> = " +
  JSON.stringify(out) +
  ";\n";
writeFileSync(resolve(process.cwd(), "lib/docs/content.ts"), ts);
console.log("Embedded:", Object.keys(out).join(", "), "→ lib/docs/content.ts");
